/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Rollcage Stage II)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80020710u
#define func_80020710 BootEntry  /* alias */
